services:
  - type: web
    name: playful
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python worker.py &
      uvicorn main:app --host 0.0.0.0 --port 8000
